services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ../laravel:/var/www/html
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /var/www/html
    depends_on:
      - sqlserver
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    environment:
      SA_PASSWORD: "ABj!010359"
      DB_HOST: "laravel-sqlserver"
      DB_DATABASE: "teste_docker_laravel"
      DB_USERNAME: "sa"
      DB_PASSWORD: "ABj!010359"
    networks:
      - laravelnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: laravel-sqlserver
    environment:
      SA_PASSWORD: "ABj!010359"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./init-sql.sh:/docker-entrypoint-initdb.d/init-sql.sh
    restart: unless-stopped
    networks:
      - laravelnet

networks:
  laravelnet:
    driver: bridge

volumes:
  sqlserverdata:
